### ISSUE TITLE
[BUG] macOS: nightlies have changed URL

### ISSUE THREAD

**Issue by maleadt** [julia-actions/setup-julia#106]
**Describe the bug**

The macOS nightlies (both x84 and aarch64) have changed URLs after the move to BuildKite. The new URLs are:
- https://julialangnightlies-s3.julialang.org/bin/macos/x64/julia-latest-macos64.dmg
- https://julialangnightlies-s3.julialang.org/bin/macos/aarch64/julia-latest-macos-aarch64.dmg

See the upload jobs in e.g. https://buildkite.com/julialang/julia-master/builds/12389.

Note that on my mac, these binaries fail to execute because they aren't properly signed (https://github.com/JuliaCI/julia-buildkite/issues/124) but I don't know whether that'll be an issue on the GitHub runners.

**Comment by SaschaMann** [comment]
Thanks for reporting this, I'd have missed it otherwise. 

I don't have a working PC right now to fix it, it might take another week or two to get to this.

**Comment by DilumAluthge** [comment]
Elliot has fixed the uploads so that the old URLs now work again.

The remaining question is if this is still an issue:

> Note that on my mac, these binaries fail to execute because they aren't properly signed (https://github.com/JuliaCI/julia-buildkite/issues/124) but I don't know whether that'll be an issue on the GitHub runners.

**Comment by maleadt** [comment]
> The remaining question is if this is still an issue:
> 
> > Note that on my mac, these binaries fail to execute because they aren't properly signed ([JuliaCI/julia-buildkite#124](https://github.com/JuliaCI/julia-buildkite/issues/124)) but I don't know whether that'll be an issue on the GitHub runners.

Not after https://github.com/JuliaCI/julia-buildkite/pull/133
