### ISSUE TITLE
[BUG] libLLVM broken for windows-latest + Julia 1.8

### ISSUE THREAD

**Issue by eahenle** [julia-actions/setup-julia#122]
**Describe the bug**
When running a CI build using `julia-actions/setup-julia@latest`, specifying Julia 1.8.1 on a `windows-latest` runner, building libraries can fail with: `ERROR: LoadError: Unable to open libLLVM!`

In particular, I encounter this error when building `FIGlet.jl`, but I have no reason to think that specific module is the problem.  Mac and Linux runners are unaffected.

**To Reproduce**
Workflow: https://github.com/eahenle/build_action_bug/blob/main/.github/workflows/mwe.yml

**Comment by SaschaMann** [comment]
Julia seems to be installed just fine in that MWE, so this doesn't look like an issue with setup-julia.

Perhaps ask on Zulip/Slack/Discourse or in https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl
