### ISSUE TITLE
Please update @actions/core to 1.10.0 

### ISSUE THREAD

**Issue by fingolfin** [julia-actions/setup-julia#123]
Right now, using `julia-actions/setup-julia` causes lots of actions due to it using an old version of `@actions/core` -- see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands

Unfortunately I know nothing about `npm` (? is that even the right tool) or how to update those dependencies here, else I'd submit a PR.

**Comment by SaschaMann** [comment]
Fixed in https://github.com/julia-actions/setup-julia/releases/tag/v1.8.3
