### ISSUE TITLE
Feature request: Allow `dev` value for `version` which installs the latest alpha, beta or release candidate release

### ISSUE THREAD

**Issue by EwoutH** [julia-actions/setup-julia#126]
It would be great of aside from the current `nightly` value for the `version` parameter (which installs the very latest nightly version), a general `dev` value could be added which installs the latest alpha, beta or release candidate version. So basically the very latest tagged release, no matter the pre-release status.

**Comment by SaschaMann** [comment]
Thanks!

I thought this was already possible through the node-semver syntax, but turns out it's not. I'll add a flag to include preleases, should be fairly straightforward.

**Comment by EwoutH** [comment]
Thanks for coming back! Did you already implement this?

**Comment by SaschaMann** [comment]
Not yet, I'll get to it on the weekend.

Or if you want, feel free to open a PR. The semver comparison takes a prerelease flag which needs to be hooked up to an input.
