### ISSUE TITLE
Question: best way to request "latest release"

### ISSUE THREAD

**Issue by ulysses4ever** [julia-actions/setup-julia#147]
I want to request the latest Julia release — is there a way to do that? `version: latest` doesn't seem to work.

**Comment by SaschaMann** [comment]
The readme contains examples: https://github.com/julia-actions/setup-julia#julia-versions

`'1'` will download the latest stable, i.e. non-prerelease, version.

**Comment by ulysses4ever** [comment]
Thank you for the reply! I read the readme several times but wasn't sure that `latest tagged version` is in fact the latest released version: a tag can be attached to anything. I suggest to change it to `latest released version` if possible.
