### ISSUE TITLE
Version specifier 1.0 is incorrectly handled

### ISSUE THREAD

**Issue by davidanthoff** [julia-actions/setup-julia#17]
It seems a version specifier of `1.0` at some stage is shortened into `1`, and then ends up downloading `1.3` instead of `1.0.5`.

**Comment by SaschaMann** [comment]
That's a bug or feature of the YAML parser used by GitHub. It reads `1.0` as a number instead of a string. `1.0` and `1` are identical and `String(1.0)` returns `"1"`. I can't think of a way to solve this because `1` is also a legitimate version. Do you have an idea?

It can be prevented by adding quotes as stated in the readme:

> **Warning:** It is strongly recommended to wrap versions in quotes. Otherwise, the YAML parser used by GitHub Actions parses certain versions as numbers which causes the wrong version to be selected. For example, 1.0 is parsed as 1.

**Comment by SaschaMann** [comment]
I asked some people who know JS way better than I do about it and they didn't know a way to tell apart `1.0` and `1` either.

The action could throw an error if the version is `1.0`/`1` instead of `'1.0'`/`'1'` so that it doesn't go unnoticed but I'm not sure if that's a better UX.

**Comment by davidanthoff** [comment]
Hm, ok, I think then maybe we'll just leave as is. I should have read the README :) I think passing it in as a string is good enough for now.

**Comment by NHDaly** [comment]
It might be nice to share the python implementation of julia's semver handling that we use in Jupyer's MyBinder to determine the julia version from the Project.toml files.

Are you allowed to use python in github actions or is it all javascript only?

Here's our custom python implementation of Julia's semver handling:
https://github.com/jupyter/repo2docker/blob/8b004e0/repo2docker/buildpacks/julia/semver.py
And here's where it's used:
https://github.com/jupyter/repo2docker/blob/8b004e0/repo2docker/buildpacks/julia/julia_project.py#L45
