### ISSUE TITLE
Idea: use GitHub’s caching feature to cache the Julia binary downloads

### ISSUE THREAD

**Issue by DilumAluthge** [julia-actions/setup-julia#18]
> Jobs on GitHub-hosted runners start in a clean virtual environment and must download dependencies each time, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate these files, GitHub can cache dependencies you frequently use in workflows.

> Use caching when you want to reuse files that don't change often between jobs or workflow runs.

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows

https://github.com/actions/cache

---

Just to clarify: my idea here is only about caching the downloaded Julia binaries. This issue is not about caching packages or package artifacts or anything like that. Just the Julia binaries, to keep it nice and simple.

**Comment by SaschaMann** [comment]
It's been on my list for a while, but the caching is still quite limited, so I didn't think it was worth it yet.

A standard build matrix can easily start 12-20 jobs, so the Julia binaries would already fill up the cache. Caching packages might be more benefitial overall for most CI setups. The cache can only be used for push/PR builds, so your bots wouldn't benefit from it either.

As I mentioned on Slack, I will update the action to check if a cached version is available and make it easier to handle in the workflow, but in the end it has to be done on the workflow level. I really hope there will be a better way in the future.

See https://github.com/actions/cache/issues/55#issuecomment-553547427 and https://github.com/actions/cache/issues/6

**Comment by staticfloat** [comment]
The Julia binaries should be shared between jobs though, right?  So you should need only a single Julia binary.

**Comment by SaschaMann** [comment]
I should have used builds or runs there to be more consistent with the proper definitions.

You can share them between jobs but every version/os combo needs a different binary. They're ~80 MB each. If you run tests on all 3 OSes and 32 bit where available, you need ~400 MB per tested Julia version. Most packages test against multiple versions and will come close to the 2 GB total cache limit if they cache the Julia binaries. You can't share the cache between repos either.

For a package it's probably more useful to cache the dependencies, which are for the most part identical across different Julia versions & OSes.

**Comment by DilumAluthge** [comment]
I think we've decided that it's better to cache artifacts and/or packages.
