### ISSUE TITLE
Create branch protection rules

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/setup-julia#2]
[This is mainly a ToDo for myself]

Create some branch protection rules. Releases branches should require signed commits, CI should pass etc.

**Comment by SaschaMann** [comment]
`releases/*`:
- Require signed commits
- Include administrators

`master`:
- Require status checks to pass before merging
    - Require branches to be up to date before merging
- Include administrators

**Comment by davidanthoff** [comment]
We should probably do the same for all the other repos. I assume there is no way to configure that org wide?

**Comment by SaschaMann** [comment]
I couldn't find an org-wide option
