### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by giordano** [julia-actions/setup-julia#208]
Node 16 is deprecated
https://github.com/julia-actions/setup-julia/blob/ffd1649f9b2d4d2608b754e0f5e24407f01d1960/action.yml#L26
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by DilumAluthge** [comment]
> Node20 [requires](https://github.com/nodejs/node/blob/v20.0.0/BUILDING.md#platform-list) glibc 2.28.
> 
> CentOS 7 [ships with](https://distrowatch.com/table.php?distribution=centos) glibc 2.17. Therefore, once we upgrade `julia-actions/setup-julia` to Node20, users that have self-hosted runners that run CentOS 7 won't be able to use new versions of the `setup-julia` action.
> 
> CentOS 7 [will become](https://www.redhat.com/en/topics/linux/centos-linux-eol) end-of-life on June 30, 2024. Therefore, I think that we should wait until June 30 to upgrade `setup-julia` to Node20.

**Comment by WardBrian** [comment]
GitHub is [suggesting](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) that node 16 support would be dropped before June:
> Our plan is to transition all actions to run on Node 20 by Spring 2024

It would be great if `v2` tag was published with node 20 support. People using runners that cannot run node 20 can stay on the previous major version, as they will currently also have to do with actions such as `cache`, `upload-artifact`, etc
