### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by logankilpatrick** [julia-actions/setup-julia#21]
Please check out https://github.com/JuliaLangSlack/StackOverflowBot/commit/9ffebb6d99395113574abc9cbb6ab108de24e421/checks?check_suite_id=367691228

I have StackOverflow in my project file but it says it's not there.

**Comment by davidanthoff** [comment]
That doesn't strike me as an issue with this action here?

**Comment by logankilpatrick** [comment]
Any suggestions to resolve it? I'm not sure what I set up wrong.

**Comment by davidanthoff** [comment]
Probably best to ask for help on the forum or on slack.

**Comment by logankilpatrick** [comment]
Will do, Thanks!
