### ISSUE TITLE
Add 'alpha' version for pre-releases like juliaup?

### ISSUE THREAD

**Issue by MilesCranmer** [julia-actions/setup-julia#227]
`juliaup` has an `alpha` channel which is used for pre-releases. As far as I can tell there is not an equivalent here? It would be great to have this. For me, the `nightly` channel is way too unstable, so I end up never using it. But I do want to test on upcoming versions. (without needing to make a PR for every single pre-release, which I never do)

I think both:

- https://github.com/julia-actions/setup-julia/issues/84
- https://github.com/julia-actions/setup-julia/issues/172

would solve this. Why not switch to juliaup? We get this for free then.

**Comment by MilesCranmer** [comment]
@IanButterworth do you know the status of your proposal and if anybody has worked on it?

**Comment by ViralBShah** [comment]
I believe https://github.com/julia-actions/setup-julia/pull/234 should address this.

**Comment by DilumAluthge** [comment]
Yeah. Fixed by #234
