### ISSUE TITLE
Problem with Strings on Windows

### ISSUE THREAD

**Issue by Crown421** [julia-actions/setup-julia#23]
After spending the day moving my Travis tests to GitHub Actions using these wonderful actions, I have however found a problem with Windows and the example. 

It appears that `"` does not get properly escaped on windows, so that this happens
```
Run julia -e 'println("Hello, World!")'
13s
##[error]Process completed with exit code 1.
Run julia -e 'println("Hello, World!")'
ERROR: UndefVarError: Hello not defined
Stacktrace:
 [1] top-level scope at none:0
##[error]Process completed with exit code 1.
```
Please see here: [Example](https://github.com/Crown421/VML.jl/runs/369960102)

After some testing, I found that the only way to make the script run everywhere was to distinguish between Windows and not Windows, as the former will work with `\"` but that will break MacOS and Linux as seen [here ](https://github.com/Crown421/VML.jl/runs/369964858)
The way it got it working is this: [Fixed](https://github.com/Crown421/VML.jl/commit/c9247fc1ca057bc83c983601c0fb21ed4d31a1f1/checks?check_suite_id=380630610)

While this is mostly irrelevant for `print` statements, it did pose a problem when installing an unregistered package via `Pkg.add(PackageSpec(url="<some url>"))`, which needs to be done separately if the tested package itself is unregistered. 
(Unregistered dependencies in unregistered packages do not appear to be resolved on their own). 

I think what I want to do is document this issue, suggest that it be added to the Readme, and maybe also that there be an action to install packages i.e. 
```
julia-actions/julia-addpkg@latest
with: 
    pkg: Unregistered
```

**Comment by davidanthoff** [comment]
I don’t think you need to escape `”` at all in your example?

**Comment by Crown421** [comment]
Yes, I apologize, I posted the wrong example. I have updated the example and the link.

**Comment by SaschaMann** [comment]
I have not tested it, but you could try using the `shell` keyword to force it to use bash, even on Windows: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell

> I think what I want to do is document this issue, suggest that it be added to the Readme

That's definitely a good idea, even if it's technically not related to this action. Could you try the workaround using `bash` and let me know if it works? If it does, I'll add it to the README.

**Comment by Crown421** [comment]
Thank you, I gave that a try [here](https://github.com/Crown421/VML.jl/commit/b9037d788fb68308f83b37d12d77258d2cb9268d/checks?check_suite_id=382289657).

Your first suggestion makes it work, which already removes the awkward `if` keyword. 

The other apparently does not quite work yet.

**Comment by SaschaMann** [comment]
I briefly looked into it, this works if you want the `- run` block to be executed like a julia file:

```yaml
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@latest
    - run: |
        println("Hello, World!")
        using InteractiveUtils; versioninfo()
      shell: bash -c "julia --color=yes --project {0}"
```

https://github.com/SaschaMann/Example.jl-1/commit/1fe2cf908d1f40f61003e8ad24f96378c99cff74/checks?check_suite_id=382303909

**Comment by Crown421** [comment]
I am not sure what caused the fail on Windows, but MKL currently fails on Windows independent of CI. 
So a better test might be to use a different unregistered package. 

A quick perusal of the Registrator shows e.g.`https://github.com/johncwok/DCCA.jl` is still unregistered (https://github.com/JuliaRegistries/General/pull/6956)

**Comment by SaschaMann** [comment]
It fails before it even gets to the `Pkg.add` line, so it's not MKL related.

---

Anyway, I'll add the `shell: bash` workaround to the README.

**Comment by Crown421** [comment]
Yes, I also tested it. 

Thank you very much, that lays my main issue to rest.

**Comment by aminya** [comment]
Anyone having the same problem:

On Github Actions, using `shell: pwsh` (which uses cross-platform PowerShell 6) and running the scripts like the following works both on Windows and Linux (using `'` around the command and escaping `"` using `\`:
```
        run: |
          julia --project -e 'using Pkg; Pkg.instantiate();'
          julia -e 'using Pkg; Pkg.add(PackageSpec(url = \"https://github.com/aminya/SnoopCompile.jl\", rev = \"multios\")); Pkg.develop(PackageSpec(; path=pwd())); using SnoopCompile; SnoopCompile.addtestdep();'
        shell: pwsh
```
`shell:bash` makes Julia think that the OS is Linux
