### ISSUE TITLE
architecture for macos-14 which is now macos-latest

### ISSUE THREAD

**Issue by ViralBShah** [julia-actions/setup-julia#241]
**Describe the bug**
macos-latest runners are now macos-14 and aarch64. In actions, these download julia for x64.

**To Reproduce**
See: https://github.com/JuliaStats/Distributions.jl/pull/1856#issuecomment-2119350142

**Expected behavior**
aarch64 platforms for macos runners should only download the aarch64 binaries or fail.

**Comment by DilumAluthge** [comment]
Similar to #240

**Comment by fonsp** [comment]
Could we do something about this? All MacOS Julia 1.6 tests are failing now... Maybe we could just silently download the x86 binary?

**Comment by DilumAluthge** [comment]
We should at least print a good error message.

**Comment by DilumAluthge** [comment]
Let me take a look at this.

**Comment by DilumAluthge** [comment]
Here is my PR to improve the error logging in this situation: #261

Here is a Discourse post to raise awareness (and provide instructions for fixing the error): https://discourse.julialang.org/t/how-to-fix-github-actions-ci-failures-with-julia-1-6-or-1-7-on-macos-latest-and-macos-14/117019
