### ISSUE TITLE
Make sure that the correct version of Julia has been installed and added to PATH

### ISSUE THREAD

**Issue by DilumAluthge** [julia-actions/setup-julia#26]
Soon, we will have Julia available by default in the GitHub Actions environment (https://github.com/actions/virtual-environments/pull/386).

This is great news for tools such as CompatHelper that do not really care what version of Julia you use (as long as it is relatively recent).

But, for example, if you are running CI for your Julia package on GitHub Actions, you probably don't want to use the default Julia - you want to use exactly the version (or versions) of Julia that you specified.

So, on e.g. package CI workflows we need to have a way of making sure that the Julia we install appears earlier in the `PATH` than does the default Julia.

**Comment by SaschaMann** [comment]
Thanks for bringing this up.

I'm not able to setup the virtual environment so I can't test it before the default Julia is actually included. I think it might just work since this action is derived from the setup-go action and go is already preinstalled.

**Comment by SaschaMann** [comment]
Actually, I think I can test it by just renaming the Julia binary to something that clashes with an existing tool.

**Comment by DilumAluthge** [comment]
@SaschaMann Should we revisit this issue now that Julia is installed by default in production?

How can we ensure that in CI workflows, the specific version of Julia that we want is the one that gets used (not the one installed by default)?

**Comment by SaschaMann** [comment]
@DilumAluthge In the [nightly test builds](https://github.com/julia-actions/setup-julia/runs/515466727?check_suite_focus=true) it works and nobody has complained yet, so I think tool-cache handles it for us?

**Comment by DilumAluthge** [comment]
Just to double check, it would be nice to look at the CI for a package that tests on multiple Julia versions (e.g. 1.0, 1.1, 1.2, 1.3) and double-check that each job uses the correct Julia versions.

Once we have checked an example like that, I think we can close this issue.

**Comment by SaschaMann** [comment]
Not a package, but it runs tests on Julia 1.0-1.3: https://github.com/exercism/v3/runs/514168920. The correct version is used everywhere.

**Comment by DilumAluthge** [comment]
Sounds great!

It might be worth re-checking that same repo in e.g. one month time to make sure that there are no regressions.

But it does seem like everything is working just fine :)

Now, we need to edit everyone's workflow files for TagBot, CompatHelper, VersionVigilante, etc. to remove the `setup-julia` steps. Since those Actions don't require specific versions of Julia, they don't need to download Julia; they should just use the local version.

**Comment by SaschaMann** [comment]
@DilumAluthge Better idea: At the end of the installation script, `julia --version` is run. I'll add an additional check that confirms that `julia --version` matches the specified version.

**Comment by DilumAluthge** [comment]
> @DilumAluthge Better idea: At the end of the installation script, `julia --version` is run. I'll add an additional check that confirms that `julia --version` matches the specified version.

That sounds perfect!

**Comment by SaschaMann** [comment]
So turns out that `core.addPath` is guaranteed to prepend it to the PATH, which means the setup-julia installed version will always be found first. Therefore I think it's not necessary to add an extra check internally.

#46 adds an output with the directory that Julia has been installed to and that has been added to the path by setup-julia. If one wants to verify that `julia` points to the correct Julia executable, one can manually check that `which julia` and the action output match.
