### ISSUE TITLE
[BUG] Error: File not found: '/home/runner/work/_actions/julia-actions/setup-julia/v2/dist/index.js'

### ISSUE THREAD

**Issue by giordano** [julia-actions/setup-julia#278]
**Describe the bug**

This action is now broken

**To Reproduce**

```yaml
      - uses: julia-actions/setup-julia@v2
```

Using version 2.4.0 just published

**Expected behavior**

The workflow doesn't crash immediately

**Screenshots/Build logs**

https://github.com/JuliaPackaging/JLLWrappers.jl/actions/runs/10636073649/job/29487082230?pr=67

**Additional context**

N/A

**Comment by IanButterworth** [comment]
Sorry, should be fixed now.

**Comment by giordano** [comment]
Is there a way to automate whatever needs to be done to publish a new release?

**Comment by IanButterworth** [comment]
That'd be nice.
The mistake I made was skipping a step in https://github.com/julia-actions/setup-julia/blob/master/devdocs/making_a_new_release.md#step-4-remove-the-dist-line-from-the-gitignore-file

The tip of that branch passed after I fixed it, but the tip wasn't where the tags were

**Comment by giordano** [comment]
Feels like all the instructions in that file should be a dispatch workflow so that you click a button and everything is done automatically.

**Comment by IanButterworth** [comment]
Indeed.

**Comment by IanButterworth** [comment]
Judging by https://github.com/JuliaPackaging/JLLWrappers.jl/pull/67 we can close this. Thanks for the fast report!

**Comment by giordano** [comment]
For example you could read the version number from `package.json` and automatically publish the version, I do something like that for a VS Code extension: https://github.com/oracc/nisaba/blob/0464b23c1af964f4fc5d0102a89ff51355b3c610/.github/workflows/tag.yml
BTW, the version number is still 2.3.0: https://github.com/julia-actions/setup-julia/blob/014c323ee07f2f2de8e278a7e7be072719976b74/package.json#L3

**Comment by IanButterworth** [comment]
Yeah, our release notes don't handle when the version on master should be updated (https://github.com/julia-actions/setup-julia/pull/279)

TagBot has a similar thing to that https://github.com/JuliaRegistries/TagBot/actions/workflows/publish.yml
