### ISSUE TITLE
Automate publishing process to avoid issues

### ISSUE THREAD

**Issue by giordano** [julia-actions/setup-julia#280]
> Feels like all the instructions in [that file](https://github.com/julia-actions/setup-julia/blob/master/devdocs/making_a_new_release.md) should be a dispatch workflow so that you click a button and everything is done automatically.

_Originally posted by @giordano in https://github.com/julia-actions/setup-julia/issues/278#issuecomment-2321943148_

**Comment by DilumAluthge** [comment]
Alternate proposal:
1. Switch to the master branch of this repo being deployable (i.e. `dist/index.js` is checked into the repo on the master branch).
2. Then, to make a new release of this repo, you just go to the Releases tab, and create a new release off of the latest commit on master.
3. Also, remove the `version` field from `package.json` and `package-lock.json`.

An added benefit of the above approach is that all PR branches will become usable, so if someone wants to try out a PR before it is merge, you just point to the PR branch.
