### ISSUE TITLE
`pkg` action

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/setup-julia#3]
GitHub [confirmed](https://twitter.com/natfriedman/status/1164210683979812869) that there will be a way to cache dependencies. While this isn't available yet, here are some thoughts that might be useful to consider for this and other actions (e.g. julia-runtest). This is rather speculative, just wanted to write it down before I forget about it.

It might be a good idea to build an action that takes care of the `Pkg` tasks that download and manage dependencies, separated from the actions that would run tests, create coverage reports and deploy docs. That way, one could use that action to download all dependencies, handle caching, if possible, to create a working environment (in the Pkg sense) with all dependencies, package `build`ing etc. in a workflow as a base for other actions to work off. Similar to how setup-julia sets up a Julia environment, the pkg action would setup a Pkg environment.

**Comment by davidanthoff** [comment]
So maybe a good split would be one action for building the package, one for testing it (that one we already have), then one for uploading coverage (or rather two, for the two services we support), and then maybe some for doc stuff?

**Comment by davidanthoff** [comment]
We now have separate actions for build, running tests and uploading coverage.
