### ISSUE TITLE
Nightly Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by aminya** [julia-actions/setup-julia#33]
https://github.com/aminya/SnoopCompile.jl/runs/757742602?check_suite_focus=true#step:3:5

**Comment by SaschaMann** [comment]
Does this happen consistently or was it a one-off issue? Sometimes GH has issues that can cause this.

**Comment by aminya** [comment]
It happened only once. Yes, probably

**Comment by SaschaMann** [comment]
There's not much we can do in the action to prevent those errors. let me know if it happens again, I'll close the issue for now.
