### ISSUE TITLE
^1.5-0 does not work

### ISSUE THREAD

**Issue by tkf** [julia-actions/setup-julia#37]
I tried (https://github.com/tkf/ThreadsX.jl/pull/131) to use Julia 1.5-rc1 with the caret syntax:

https://github.com/julia-actions/setup-julia/blob/3eb3524cb46772bc21de3489a0d28f0d0c6ee213/README.md#L44-L45

The first syntax `^1.5.0-rc1` worked but the second syntax `^1.5-0` didn't work.  I also tried `^1.5` and `^1.5.0` wondering if `^1.3-0` was some kind of typo but they didn't work.

It'd be nice if the documentation and the implementation match.

**Comment by SaschaMann** [comment]
That's a typo, it should be `^1.5.0-0`. Thanks for the report :) 

Fixed by https://github.com/julia-actions/setup-julia/commit/c766abf0da2560df5bef417e602aefe3f1e721c1

**Comment by SaschaMann** [comment]
More fixes here: https://github.com/julia-actions/setup-julia/commit/477bec664cb24baff89854e7cf053f49c0b60637

I mixed up tilde and caret ranges as well in the examples.

**Comment by tkf** [comment]
Ah, great. Thanks for documenting the subtle differences!
