### ISSUE TITLE
Improve error mesage when a julia version that has not been released is specified

### ISSUE THREAD

**Issue by oxinabox** [julia-actions/setup-julia#38]
I mistakenly said to use Julia 1.6.
This is the error i got. https://github.com/oxinabox/LayeredLayouts.jl/pull/1/checks?check_run_id=827944196

But I don't see any error except the red cross, so I couldn't workout what what wrong.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/5127634/86520847-f40e8c80-be40-11ea-8b0a-34ac15e1b146.png">

**Comment by SaschaMann** [comment]
Now it looks like this:

![grafik](https://user-images.githubusercontent.com/20866761/86532457-5cee1700-beca-11ea-864d-366cec71c895.png)

![grafik](https://user-images.githubusercontent.com/20866761/86532463-65dee880-beca-11ea-8566-440bc55474e7.png)
