### ISSUE TITLE
Support for release nightlies

### ISSUE THREAD

**Issue by maleadt** [julia-actions/setup-julia#62]
It would be useful if this action supports using versioned nightlies, e.g. `https://julialangnightlies-s3.julialang.org/bin/linux/x64/1.6/julia-latest-linux64.tar.gz` from the `release-1.6` branch to test the upcoming 1.6 release.

I recently added that feature to the JuliaGPU BuildKite CI, https://github.com/JuliaCI/julia-buildkite-plugin/commit/75c360c267d9c3b006dd7fcd0177159909645c55, using these nightlies when the user requests `version: "1.6-nightly"`.

**Comment by DilumAluthge** [comment]
This would be a great feature to have.

**Comment by SaschaMann** [comment]
I didn't know those existed, I'll add them 👍
