### ISSUE TITLE
Benchmark if Windows installer or Windows archive is faster to install

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/setup-julia#64]
Recent versions of Julia are also shipped as a portable .zip file for Windows. That may or may not be faster than running the installer.

**Comment by IanButterworth** [comment]
Zip is slightly faster but still slow https://github.com/julia-actions/setup-julia/pull/171

Supposedly the windows installers might be more compressed than other platforms, so might be unavoidably slower

**Comment by IanButterworth** [comment]
`.tar.gz` wins! https://github.com/julia-actions/setup-julia/pull/171
They were added for use by juliaup, so we should be able to rely on their existence.
