### ISSUE TITLE
[BUG] Could not find a Julia version that matches 1.6

### ISSUE THREAD

**Issue by fingolfin** [julia-actions/setup-julia#66]
On https://discourse.julialang.org/t/julia-v1-6-0-beta1-is-now-available/53065 it is said that Julia 1.6 is available now on GitHub Actions. But it is not, see e.g. [here](https://github.com/oscar-system/Singular.jl/pull/346/checks?check_run_id=1671666407) which shows this:
```
Run julia-actions/setup-julia@v1
  with:
    version: 1.6
    arch: x64
    show-versioninfo: false
Error: Could not find a Julia version that matches 1.6
```

---

Summary of the solution (@fonsp's [comment](https://github.com/julia-actions/setup-julia/issues/66#issuecomment-759783954)):

> # To summarize
> 
> Use `"^1.6.0-0"` as your version specifier instead of `"1.6"` while 1.6 is in beta, example: https://github.com/julia-actions/setup-julia/pull/69/files

**Comment by fredrikekre** [comment]
I believe this needs to be rerun manually or wait for this cronjob https://github.com/SaschaMann/Julia-versions.json/blob/797e1623674b48f55c2701ace022161371e5f153/.github/workflows/build-versions-file.yml#L6

**Comment by DilumAluthge** [comment]
Yeah I think that's it.

@SaschaMann and I are working on transferring that script to an appropriate organization, so we can have multiple people who have the permission to run workflow dispatches. We just haven't finalized it yet.

**Comment by SaschaMann** [comment]
I triggered a manual rerun, it should be available soonish (~30 min + however long cache invalidation takes I guess). The script itself takes a rather long time to run which is why bumping the frequency isn't really an option as a quick fix.

**Comment by DilumAluthge** [comment]
Passing a message along from @SaschaMann 

> I just realised it may not actually work as 1.6. I believe the syntax for pre-releases is ^1.6.0-0

**Comment by fingolfin** [comment]
Then perhaps that discourse announcement should be adjusted? (And next time perhaps first checked for accuracy ;-), no offense intended)

**Comment by SaschaMann** [comment]
Dilum posted the same comment in the thread. But yeah, it should be adjusted in the future or I need to find a way to make `'1.6'` work for pre-releases without explicit special casing and without breaking `'1'` or potentially jumping from `1.6.0` to `1.6.1-rc1` if those would ever become a thing.

There's a list of examples in the README to figure out which version to use: https://github.com/julia-actions/setup-julia#julia-versions

**Comment by vlandau** [comment]
I'm getting the same error with '^1.6.0-0'. Should I try '1.6-nightly'?

**Comment by SaschaMann** [comment]
Could you link the build? It works as intended in #69.

`1.6-nightly` is a different build, I think, as it's built straight from the release branch while beta1 is fixed to one commit.

**Comment by vlandau** [comment]
Ack! Sorry, it is working :facepalm: Totaly got my wires crossed and forget that the failure was from another issue on my end. Sorry for the confusion.

**Comment by SaschaMann** [comment]
No worries :)

**Comment by fonsp** [comment]
# To summarize

Use `"^1.6.0-0"` as your version specifier instead of `"1.6"` while 1.6 is in beta, example: https://github.com/julia-actions/setup-julia/pull/69/files

**Comment by SleeplessByte** [comment]
(Correct. That's semver)

**Comment by DilumAluthge** [comment]
Closing this, as there is nothing to do.

The next time we have a Discourse announcement for a beta or an RC, we should make sure to mention that for GitHub Actions, you should use the `"^1.6.0-0"` version specifier. cc: @kristofferc @ararslan

**Comment by DilumAluthge** [comment]
@SaschaMann Out of curiosity, once we have the 1.6-rc1, when you use "^1.6.0-0" on GitHub Actions, what gets picked? The 1.6-rc1? Or the 1.6-beta1?

**Comment by SaschaMann** [comment]
1.6.0-rc1.

It follows standard semver resolving, similar to Julia's:

```
julia> v"1.6.0-rc1" > v"1.6.0-beta1"
true
```

**Comment by DilumAluthge** [comment]
Perfect!
