### ISSUE TITLE
[BUG] ^1.6.0-0 checksum error

### ISSUE THREAD

**Issue by fonsp** [julia-actions/setup-julia#72]
```
Run julia-actions/setup-julia@v1
Error: Checksum of downloaded file does not match the expected checksum from versions.json.
Expected: dafa3431861b8aa4a82f0885f84b21a39332f1e931c09660af70ad25a716eec8
Got: 7e6a0298eebe48d408279c6f99cb5df575b39097c44846971e5851a4daf25f0a
```

https://github.com/fonsp/Pluto.jl/runs/1871653407?check_suite_focus=true

**Comment by SaschaMann** [comment]
Thanks!

I triggered a rebuild of the versions file (should be done in ~30-45 min). Perhaps the binary changed after it first ran due to macOS signing nonsense. Let me know if it persists.

**Comment by DilumAluthge** [comment]
FWIW I think the original macOS build was an assertions build. They've fixed that, and the macOS build should now be a non-assertions build.

**Comment by SaschaMann** [comment]
The file has been updated and the expected hash is now `7e6a0298eebe48d408279c6f99cb5df575b39097c44846971e5851a4daf25f0a`. There were some issues with the update script so it didn't run automatically every 24 hours that I've hotfixed.

Please let me know if it breaks again
