### ISSUE TITLE
MacOS Julia 1.8.0 takes 6 minutes

### ISSUE THREAD

**Issue by fonsp** [julia-actions/setup-julia#95]
On Linux, setup-julia with 1.8 takes 10 seconds, on windows 40 seconds, but on MacOS, it takes 6 minutes:

Workflow run:
https://github.com/fonsp/Pluto.jl/runs/5382039907?check_suite_focus=true

Screenshot:

<img width="993" alt="Schermafbeelding 2022-03-03 om 11 33 51" src="https://user-images.githubusercontent.com/6933510/156547697-343a69ec-3ff4-46de-91d2-63b8b2edbba0.png">

**Comment by SaschaMann** [comment]
Does this happen repeatedly?

I can't reproduce it in my tests: https://github.com/julia-actions/setup-julia/runs/5406283469?check_suite_focus=true & https://github.com/julia-actions/setup-julia/runs/5406254151?check_suite_focus=true

There might have been some random connection issues with the runner when trying to download the binary. It retries downloading it with an exponential backoff if something goes wrong, so it sometimes takes a while if there's a temporary issue with the download.

---

If it does happen repeatedly, please [enable debug logs](https://github.com/actions/toolkit/blob/main/docs/action-debugging.md#how-to-access-step-debug-logs) and post the full log of that step.

**Comment by giordano** [comment]
Yeah, I think it was a random connection problem, I haven't seen that the whole day.
